### ISSUE TITLE
Some Error for the workflow in Chinese

### ISSUE THREAD

**Issue by wlhgtc** [jasonshanks/alfred-workflow-toggle-airpods#3]

**Comment by wlhgtc** [comment]
/Users/hgtc/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/DF1E7823-5A7C-4DC2-B066-F93B055951AC:433:501: execution error: “System Events”遇到一个错误(with an error)：不能获得(can not find )“menu bar item 1 of menu bar 1 of process "SystemUIServer" whose description contains "bluetooth"”。无效的索引(invalid index)。 (-1719)
This is an error when I debug in alfred. I add some note with these Chinese descripition using "()".

**Comment by wlhgtc** [comment]
I wonder which part (such as "System Events","bluetooth") should be replaced by Chinese in this Scripit.

**Comment by wlhgtc** [comment]
After test, this error occurs in 
`	tell process "SystemUIServer"
		set btMenu to (menu bar item 1 of menu bar 1 whose description contains "bluetooth")`
Seem it tries to find the description contains "bluetooth". How can I get all description in "SystemUIServer" ? I may can find the right description in Chinese.

**Comment by Raphus-cucullatus** [comment]
@wlhgtc This line of code works in my environment.  (My system language is also Chinese)
Just a guess, do you have "bluetooth" icon in your menu bar?  
![a](https://user-images.githubusercontent.com/16362275/60757608-75212100-a03f-11e9-9e90-43aa6fae79a5.png)

**Comment by wlhgtc** [comment]
No, I don't show it on my menu. Maybe this is the reason?

**Comment by Raphus-cucullatus** [comment]
If it is not showed, then it can not be found in the menu bar :P

**Comment by wlhgtc** [comment]
Got it, thanks!!!

**Comment by Raphus-cucullatus** [comment]
BTW~ if you still want to check the description of all the menu bar items, you can run
```applescript
tell application "System Events"
	tell process "SystemUIServer"
		repeat with i in (every menu bar item of menu bar 1)
			set content to the description of i
			display dialog content
		end repeat
	end tell
end tell
```
